<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT5ioH2Y\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT5ioH2Y/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerT5ioH2Y.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerT5ioH2Y\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerT5ioH2Y\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'T5ioH2Y',
    'container.build_id' => 'ba8614d7',
    'container.build_time' => 1554402521,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT5ioH2Y');
